---
title: "Analysis and Conclusion"
output: 
  html_document:
    fig_caption: no
    number_sections: no
    toc: no
    toc_float: false
    collapsed: no
---

```{r set-options, echo=FALSE}
options(width = 105)
knitr::opts_chunk$set(dev='png', dpi=300, cache=TRUE)
pdf.options(useDingbats = TRUE)
```

# Conclusion:

## Bootstrap Results

As we can see, our observed value is always more than our highest confidence interval. This can happen for a couple of reasons, but mainly, I think what we have here is that there may be outliers and bias in our data. We see vast change in differences from year to year, but we are also only looking at a tiny subset of the data we started with, when we continuously subset we are potentially introducing bias into the simulation, which can result in an observed statistic that is way out in left field, this also indicates that our observed mean difference is not an accurate represendation of the population.


## Thoughts Moving Forward

This data set was challenging to use for statistical analysis, it is missing vast amounts of information, and oftentimes the same study or studies done by the same author share certain features, but lack others, this resulted in a very small subset being selected. I also want to note that this is only exploratory and I am not drawing any major conclusions about the findings from the simulation, only observing. I think moving forward with this set I would want to instead, find the mean difference using all country data, I thought being more selective would narrow down the features variance, however, I think I may have introduced selective bias into the simulation. \
\
I feel that I understand how to move through this data set more efficiently, and also believe there are many more exploratory branches to climb. If I were to formulate a question before sub-setting, then we would be able to run simulations and take the results more seriously. This would be the case because sub-setting then coming up with a question is already a biased approach.\ 
\
In future earth science exploratory analysis, I might try to find a data set that is fuller, and less broad in its features, then I will have more time and energy to be able to run other types of analysis. \



## Citations: 

### Main Dataframe: 
Jian, J., R. Vargas, K.J. Anderson-Teixeira, E. Stell, V. Herrmann, M. Horn, N. Kholod, J. Manzon, R. Marchesi, D. Paredes, and B.P. Bond-Lamberty. 2021. A Global Database of Soil Respiration Data, Version 5.0. ORNL DAAC, Oak Ridge, Tennessee, USA. https://doi.org/10.3334/ORNLDAAC/1827




### References:

Alboukadel. (2019, December 25). GGPlot gradient color : Best reference. Datanovia. https://www.datanovia.com/en/blog/ggplot-gradient-color/ /\

Bartlein, P. (2014). R for Earth-System Science. R for earth-system science. https://pjbartlein.github.io/REarthSysSci/index.html 


Basetheme\.README\.(n.d.)\.https://cran.r-project.org/web/packages/basetheme/readme/README.html#:~:text=The%20basetheme()%20function%20provides,the%20graphics%20device%20is%20closed. 


Christoph Hanck, M. A. (2024, February 13). Introduction to econometrics with R. 5.2 Confidence Intervals for Regression Coefficients. https://www.econometrics-with-r.org/5.2-cifrc.html 


GfG. (2021, July 10). Bootstrap confidence interval with R programming. GeeksforGeeks. https://www.geeksforgeeks.org/bootstrap-confidence-interval-with-r-programming/ 


GfG. (2023, December 21). Remove rows with NA in one column of R dataframe. GeeksforGeeks. https://www.geeksforgeeks.org/remove-rows-with-na-in-one-column-of-r-dataframe/ 


GGPLOT2 add straight lines to a plot : Horizontal, vertical and regression lines. STHDA. (n.d.). http://www.sthda.com/english/wiki/ggplot2-add-straight-lines-to-a-plot-horizontal-vertical-and-regression-lines 


Head: Return the first or last part of an object. RDocumentation. (n.d.). https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/head 


Khan Academy. (n.d.). Interpreting a confidence interval for a mean (article). Khan Academy. https://www.khanacademy.org/math/ap-statistics/xfb5d8e68:inference-quantitative-means/one-sample-t-interval-mean/a/interpret-one-sample-t-interval-mean 


Konrad, M. (2019, April 30). Zooming in on maps with SF and Ggplot2: R-bloggers. R. https://www.r-bloggers.com/2019/04/zooming-in-on-maps-with-sf-and-ggplot2/ 


xiaodai. (n.d.). R: How to make second level indented bullet points using RMarkdown ioslides?. Stack Overflow. https://stackoverflow.com/questions/26666839/r-how-to-make-second-level-indented-bullet-points-using-rmarkdown-ioslides 


