
---
title:  Exploratory Data Analysis and General Cleaning
output:
  html_document:
    fig_caption: no
    number_sections: no
    toc: no
    toc_float: false
    collapsed: no
---

```{r set-options, echo=FALSE, strip.white=TRUE}
options(width = 105)
knitr::opts_chunk$set(dev='png', dpi=300, cache=TRUE)
pdf.options(useDingbats = TRUE)
```

# Introduction #
Data Inspection and Cleaning:
```{r}
library(readr)
soil <- read_csv("SRDB_V5_1827/data/srdb-data-V5.csv", col_types = cols(.default = "c"))
head(soil)
```

# Exploring the Data:
First let's look at where the data is from. Here we see the top 12 most frequent countries represented in the set:
```{r}
ggplot(data = soil) + geom_bar(mapping = aes(x = Country))
```
First we will load the data and plot the locations of all the historic measurements by latitude and longitude. 

```{r}
library("maps")
library("mapdata")
library("ggplot2")
library("readr")
```

```{r}
background_map <- map_data("worldHires")
soil_samps <- read_csv("SRDB_V5_1827/data/srdb-data-V5.csv")

```
```{r}
#adding our map:
ggplot() +
  geom_polygon(data = background_map, aes(x = long, y = lat, group = group), fill = "lightgrey") +
  geom_point(data = soil_samps, aes(x = Longitude, y = Latitude), color = "red", size = 0.5) +
  coord_fixed() +
  labs(title = "Map of Soil Sample Sites", x = "Longitude", y = "Latitude")
```

